trigger:
- development

pool:
  name: default
  

stages:
- stage: build  

  jobs:
  - job: windows
    steps:
    - checkout: self
      lfs: true
      persistCredentials: true

    # - checkout: MyDevops1  

    - task: powershell@2
      inputs: 
        targetType: 'inline'
        script: |
          Write-Host "Hi siddharth"

- stage: build2 
  jobs:
  - job: windows2
    steps:
    - checkout: self
      lfs: true
      persistCredentials: true

    # - checkout: MyDevops1  
    # - task: powershell@2
    #   inputs: 
    #     targetType: filepath
    #     filepath: '$(Build.SourceDirectory)\PRACTICE-Pipeline\MyDevops1\pipelinetest\practice.ps1'
    #     errorActionPreference: continue

      - powershell: |
   
          $window = New-Object Windows.Window

          $window.Title = $window.Content = “Hello World.  Check out PowerShell and WPF Together.”

          $window.SizeToContent = “WidthAndHeight”

          $null = $window.ShowDialog()                   