trigger:
- master

pool:
  name: default
  
steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

steps:
- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build'

steps:
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: build